# Generated by Django 5.2.9 on 2026-01-14 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(db_index=True, max_length=1024, unique=True)),
                ('file_hash', models.CharField(max_length=64)),
                ('file_size', models.BigIntegerField()),
                ('keywords', models.JSONField(default=list)),
                ('is_minecraft', models.BooleanField(default=False)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('tokens_used', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-processed_at'],
            },
        ),
    ]
