# Generated by Django 6.0 on 2025-12-21 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jarvis', '0002_remove_chatmessage_username_chatmessage_player_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='chatmessage',
            constraint=models.UniqueConstraint(fields=('player', 'timestamp', 'content'), name='unique_chat_message'),
        ),
    ]
