# Generated by Django 5.2.9 on 2025-12-21 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jarvis', '0005_clauderesponse_toolexecution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='description',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
