# Generated by Django 5.2 on 2025-12-23 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jarvis', '0006_alter_location_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='location_screenshots/'),
        ),
    ]
