# Generated by Django 5.2.9 on 2025-12-25 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jarvis', '0007_location_screenshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='MinecraftTrivia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fact', models.CharField(default='', max_length=250)),
                ('last_used', models.DateTimeField(default=None, null=True)),
            ],
            options={
                'ordering': ['last_used'],
            },
        ),
    ]
