# Generated by Django 5.2 on 2025-12-26 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jarvis', '0008_minecrafttrivia'),
    ]

    operations = [
        migrations.AddField(
            model_name='minecraftplayer',
            name='last_login_x',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='minecraftplayer',
            name='last_login_y',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='minecraftplayer',
            name='last_login_z',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='minecraftplayer',
            name='loot_last_given',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
