# Generated by Django 5.2.10 on 2026-02-21 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jarvis', '0009_explorer_rewards'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='dimension',
            field=models.CharField(default='overworld', max_length=20),
        ),
    ]
