server {
    listen 8080;
    server_name minecraft.aquapony.com 192.168.42.123 localhost;
    client_max_body_size 10M;

    location /static/ {
        alias /home/efstone/PycharmProjects/claudemc/staticfiles/;
    }

    location /media/ {
        alias /home/efstone/PycharmProjects/claudemc/media/;
    }

    location / {
        proxy_pass http://unix:/run/gunicorn/claudemc.sock;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
